# remove current config with: 
# rm ~/.labelmerc
auto_save: true
display_label_popup: false # set to false for fast point clicks
store_data: false # image data in json is not needed
keep_prev: false
keep_prev_scale: true
keep_prev_brightness: false
keep_prev_contrast: true
logger_level: info
next_on_click: true # move to next image on click
delete_similar_on_click: true # delete similar labels on click

flags: {need_help: false}
label_flags: {'labeler_Gijs': false}

labels: [example_label1, example_label2]
file_search: null
sort_labels: false # When false actually sorts items. Dont change this
validate_label: null
lastOpenDir: null

default_shape_color: [0, 255, 0]
shape_color: auto  # null, 'auto', 'manual'
shift_auto_shape_color: 0
label_colors: null

shape:
  # drawing
  line_color: [0, 255, 0, 128]
  fill_color: [0, 255, 0, 0]  # transparent
  vertex_fill_color: [0, 255, 0, 255]
  # selecting / hovering
  select_line_color: [255, 255, 255, 255]
  select_fill_color: [0, 255, 0, 155]
  hvertex_fill_color: [255, 255, 255, 255]
  point_size: 8

# main
flag_dock:
  show: true
  closable: true
  movable: true
  floatable: true
label_dock:
  show: true
  closable: true
  movable: true
  floatable: true
shape_dock:
  show: true
  closable: true
  movable: true
  floatable: true
file_dock:
  show: true
  closable: true
  movable: true
  floatable: true

# label_dialog
show_label_text_field: true
label_completion: startswith
fit_to_content:
  column: true
  row: false

# canvas
epsilon: 10.0
canvas:
  # None: do nothing
  # close: close polygon
  double_click: close
  # The max number of edits we can undo
  num_backups: 10
  # show crosshair. Useful during labeling, adds a horizontal and vertical line to the image.
  crosshair:
    polygon: false
    rectangle: true
    circle: false
    line: false
    point: false
    linestrip: false
    polygonSAM: false

# segment anything related parameters
sam:
  weights: vit_h # vit_h, vit_l or vit_b
  maxside: 1280 # will downsize the image during inference to the maxsize.
  approxpoly_epsilon: 1 # adjust the poylgon simplification algorithm. The large the less vertices.
  device: "cuda" # "cuda" or "cpu"

shortcuts:
  close: Ctrl+W
  open: Ctrl+O
  open_dir: Ctrl+U
  quit: Ctrl+Q
  save: Ctrl+S
  save_as: Ctrl+Shift+S
  save_to: null
  delete_file: Ctrl+Delete

  open_next: [D, Ctrl+Shift+D, Right]
  open_prev: [A, Ctrl+Shift+A, Left]
  sam_run_video: S

  zoom_in: [Ctrl++, Ctrl+=]
  zoom_out: Ctrl+-
  zoom_to_original: Ctrl+0
  fit_window: Ctrl+F
  fit_width: Ctrl+Shift+F

  create_sam_polygon: W
  sam_hide: Q
  sam_stop: Z
  create_polygon: Ctrl+N
  create_rectangle: Ctrl+R
  create_circle: null
  create_line: null
  create_point: null
  create_linestrip: null
  edit_polygon: Ctrl+Jq
  delete_polygon: Delete
  duplicate_polygon: Ctrl+D
  copy_polygon: Ctrl+C
  paste_polygon: Ctrl+V
  undo: Ctrl+Z
  undo_last_point: Ctrl+Z
  add_point_to_edge: Ctrl+Shift+P
  edit_label: Ctrl+E
  toggle_keep_prev_mode: Ctrl+P
  remove_selected_point: [Meta+H, Backspace]
  prev_label: [Up]
  next_label: [Down]